require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarreersController do

  # This should return the minimal set of attributes required to create a valid
  # Carreer. As you add validations to Carreer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CarreersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all carreers as @carreers" do
      carreer = Carreer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:carreers).should eq([carreer])
    end
  end

  describe "GET show" do
    it "assigns the requested carreer as @carreer" do
      carreer = Carreer.create! valid_attributes
      get :show, {:id => carreer.to_param}, valid_session
      assigns(:carreer).should eq(carreer)
    end
  end

  describe "GET new" do
    it "assigns a new carreer as @carreer" do
      get :new, {}, valid_session
      assigns(:carreer).should be_a_new(Carreer)
    end
  end

  describe "GET edit" do
    it "assigns the requested carreer as @carreer" do
      carreer = Carreer.create! valid_attributes
      get :edit, {:id => carreer.to_param}, valid_session
      assigns(:carreer).should eq(carreer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Carreer" do
        expect {
          post :create, {:carreer => valid_attributes}, valid_session
        }.to change(Carreer, :count).by(1)
      end

      it "assigns a newly created carreer as @carreer" do
        post :create, {:carreer => valid_attributes}, valid_session
        assigns(:carreer).should be_a(Carreer)
        assigns(:carreer).should be_persisted
      end

      it "redirects to the created carreer" do
        post :create, {:carreer => valid_attributes}, valid_session
        response.should redirect_to(Carreer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved carreer as @carreer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Carreer.any_instance.stub(:save).and_return(false)
        post :create, {:carreer => {}}, valid_session
        assigns(:carreer).should be_a_new(Carreer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Carreer.any_instance.stub(:save).and_return(false)
        post :create, {:carreer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested carreer" do
        carreer = Carreer.create! valid_attributes
        # Assuming there are no other carreers in the database, this
        # specifies that the Carreer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Carreer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => carreer.to_param, :carreer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested carreer as @carreer" do
        carreer = Carreer.create! valid_attributes
        put :update, {:id => carreer.to_param, :carreer => valid_attributes}, valid_session
        assigns(:carreer).should eq(carreer)
      end

      it "redirects to the carreer" do
        carreer = Carreer.create! valid_attributes
        put :update, {:id => carreer.to_param, :carreer => valid_attributes}, valid_session
        response.should redirect_to(carreer)
      end
    end

    describe "with invalid params" do
      it "assigns the carreer as @carreer" do
        carreer = Carreer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Carreer.any_instance.stub(:save).and_return(false)
        put :update, {:id => carreer.to_param, :carreer => {}}, valid_session
        assigns(:carreer).should eq(carreer)
      end

      it "re-renders the 'edit' template" do
        carreer = Carreer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Carreer.any_instance.stub(:save).and_return(false)
        put :update, {:id => carreer.to_param, :carreer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested carreer" do
      carreer = Carreer.create! valid_attributes
      expect {
        delete :destroy, {:id => carreer.to_param}, valid_session
      }.to change(Carreer, :count).by(-1)
    end

    it "redirects to the carreers list" do
      carreer = Carreer.create! valid_attributes
      delete :destroy, {:id => carreer.to_param}, valid_session
      response.should redirect_to(carreers_url)
    end
  end

end
